executable = runSampleGen_EE_minus.sh
arguments             = 1000 1100 300 $(ClusterId)
output                = output/myjob.$(ClusterId).$(ProcId).out
error                 = output/myjob.$(ClusterId).$(ProcId).err
log                   = output/myjob.$(ClusterId).log
should_transfer_files=YES
request_memory = 3.0 GB
+MaxRuntime = 6*24*60*60
+SingularityImage = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el7:x86_64"
+SingularityBindCVMFS = True
when_to_transfer_output = ON_EXIT_OR_EVICT
queue
